# NumPy
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you don't have Anaconda, install NumPy by going to your terminal or command prompt and type:**
    
    !pip install numpy
    conda install numpy
    


In [3]:
!pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [4]:
import numpy as np

In [5]:
sales=[10,20,30,40]
type(sales)# double the sales for next week target

list

In [6]:
target=[]
for i in sales:
    target.append(i*2)
print(target)  # here we use loop function to double the sale

[20, 40, 60, 80]


In [8]:
arr=np.array(sales)  # it's easy and faster execution 
type(arr)

numpy.ndarray

In [11]:
double_sales=arr*2
double_sales

array([20, 40, 60, 80])

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation.

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [12]:
  arr1 = np.array([])   # create an empty array
  arr1

array([], dtype=float64)

In [13]:
type(arr1) 

numpy.ndarray

In [14]:
l1=[]
type(l1)

list

In [15]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [24]:
a=np.array(my_list)
a

array([1, 2, 3, 4, 5])

In [26]:
my_list+[2] # it's concat  

[1, 2, 3, 4, 5, 2]

In [27]:
a+[2] # it will add the value to the each element in the array

array([3, 4, 5, 6, 7])

In [28]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [29]:
a.ndim  # number of dimensions in the array

1

In [30]:
a.size  # size of an array is the no. of items

5

In [31]:
len(a)

5

In [32]:
a.shape # shape of array

(5,)

#### Arrays can be of n dimensions.

In [33]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists(Nested list)

In [34]:
b=np.array(my_matrix) # generates a 2-d array
b 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
# Array summary
print('The Dimension of array : ',b.ndim) # dimensions of given array

The Dimension of array :  2


In [37]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [38]:
print('The datatype of element:',b.dtype) # Datatype of elements in array

The datatype of element: int64


In [39]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [40]:
print('The shape:',b.shape)

The shape: (3, 4)


In [41]:
arr2= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr2.ndim # 3d array

3

In [44]:
arr2.shape

(2, 2, 3)

In [51]:
arr2[1][1][2]

np.int64(12)

In [52]:
arr3=np.array(["this",'is'])
arr3

array(['this', 'is'], dtype='<U4')

In [53]:
arr3.ndim

1

In [54]:
arr3.size

2

## Built-in Methods

There are lots of built-in ways to generate Arrays

### Reshape function

In [55]:
d2=np.array([[1,2,3],[3,4,5]])
d2

array([[1, 2, 3],
       [3, 4, 5]])

In [56]:
d2.ndim

2

In [58]:
d2.size

6

In [59]:
d2.shape

(2, 3)

In [60]:
d2.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

In [61]:
d2.reshape(-1) #it's converting into 1D array

array([1, 2, 3, 3, 4, 5])

In [62]:
d3=[[[1,2,3],[4,5,6],[7,8,9],[7,8,9]]]

In [63]:
d_3=np.array(d3)

In [64]:
d_3.ndim

3

In [65]:
d_3.size

12

In [68]:
d_3.reshape(1,2,6)

array([[[1, 2, 3, 4, 5, 6],
        [7, 8, 9, 7, 8, 9]]])

In [70]:
d_3.reshape(1,1,1,4,3)

array([[[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [7, 8, 9]]]]])

### arange

Return evenly spaced values within a given interval.

In [74]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [81]:
np.arange(20) # end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
np.arange(2,15) # start, end and step

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
np.arange(0,10,2) # start end and step

array([0, 2, 4, 6, 8])

In [87]:
# 1 - 100 interval of 10
np.arange(10,101,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [88]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### zeros and ones
Generate arrays of zeros or ones

In [90]:
np.zeros(8) # Generates array in 1 dimension with all elements 0

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
np.zeros((5,5))  # Generates array in 2 diemnsions with all elements 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [92]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [93]:
np.ones(5) # Generates array of 1 dimension where all elements are 1

array([1., 1., 1., 1., 1.])

In [98]:
a=np.ones((4,5,6))
print(a)
print(a.dtype)# Generates array of 3 dimensions where all elements are 1, 4-no_blocks, 5-rows, 6-columns

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
float64


In [100]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

### linspace
Return evenly spaced numbers over a specified interval.

In [105]:
np.linspace(1,10)  # default 50 observations
# both the start and end are included in the array

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [113]:
np.linspace(0,1000,10)

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [103]:
np.linspace(1,15)  # default 50 observations
# both the start and end are included in the array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [146]:
time=np.linspace(0,10)
pri=1000
rate=.05
amount=pri*np.exp(rate*time)
amount

array([1000.        , 1010.25632081, 1020.61783373, 1031.08561765,
       1041.66076253, 1052.34436948, 1063.13755093, 1074.04143072,
       1085.05714419, 1096.18583835, 1107.42867198, 1118.78681571,
       1130.2614522 , 1141.85377625, 1153.5649949 , 1165.39632755,
       1177.34900616, 1189.42427527, 1201.62339221, 1213.94762721,
       1226.39826351, 1238.97659754, 1251.683939  , 1264.52161102,
       1277.49095033, 1290.59330735, 1303.83004634, 1317.20254557,
       1330.71219745, 1344.36040865, 1358.14860028, 1372.07820802,
       1386.1506823 , 1400.36748838, 1414.73010659, 1429.24003242,
       1443.8987767 , 1458.70786577, 1473.6688416 , 1488.783262  ,
       1504.05270075, 1519.47874776, 1535.06300926, 1550.80710794,
       1566.71268314, 1582.78139104, 1599.01490475, 1615.41491459,
       1631.98312819, 1648.7212707 ])

In [ ]:
# retstep ~ return step computed by linspace

In [147]:
np.linspace(0,25, retstep=True) # Start # end (Here end is included) and default elements are 50

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 np.float64(0.5102040816326531))

In [150]:
np.linspace(0,200,10) # default retstep=False

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [151]:
np.linspace(0,200,10,retstep=True)

(array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889, 111.11111111, 133.33333333, 155.55555556,
        177.77777778, 200.        ]),
 np.float64(22.22222222222222))

### eye

Creates an identity matrix

In [2]:
import numpy as np
np.eye(4)   

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
# generates 2d array of (5,5)
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Broadcasting in an array
method of accessing the each and every elements in array

In [10]:
big_one=np.ones((3,4),dtype=int)
print(big_one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
big_one.dtype

dtype('int64')

In [21]:
a=big_one + 3
a

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [23]:
b=a*2/4
b

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [19]:
big_one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
bigger_one=big_one*6 - 3
bigger_one

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [159]:
bigger_one/2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [24]:
arr1 = np.arange(20)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
arr1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [27]:
arr=np.arange(4)
arr

array([0, 1, 2, 3])

In [28]:
arr + arr # add

array([0, 2, 4, 6])

In [30]:
arr

array([0, 1, 2, 3])

In [29]:
arr  ** 2 # square

array([0, 1, 4, 9])

### Use of Copy function
copy function retains the original. copy creates a backup array.

In [31]:
a1=np.arange(2,10)
a1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a2=a1
a2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b1=a1.copy() # copying the original array
print(b1)
print(b1.size)

[2 3 4 5 6 7 8 9]
8


In [43]:
b1[1:]=99 # i want all the values 88 from index 2

In [44]:
b1 # modified array

array([ 2, 99, 99, 99, 99, 99, 99, 99])

In [45]:
a1 # original array remain same 

array([2, 3, 4, 5, 6, 7, 8, 9])

## Random number generation

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [62]:
np.random.rand()

0.90531777248447

In [65]:
np.random.rand(100) # rand gives values between 0 and 1

array([0.63710821, 0.03687217, 0.77560564, 0.19135875, 0.03477034,
       0.62042315, 0.10471264, 0.71193979, 0.71547198, 0.78643579,
       0.80890433, 0.08266473, 0.53866896, 0.31457208, 0.27451709,
       0.22890503, 0.63058662, 0.80811562, 0.99181774, 0.4879261 ,
       0.24006828, 0.59399616, 0.8649849 , 0.42020363, 0.60748324,
       0.57929112, 0.29052171, 0.94367492, 0.76782298, 0.58102294,
       0.61221895, 0.77178051, 0.73645503, 0.10070582, 0.4293883 ,
       0.92141873, 0.73300124, 0.80695156, 0.81317429, 0.3897184 ,
       0.23651897, 0.90762542, 0.01117635, 0.56191684, 0.59127732,
       0.74067467, 0.14043304, 0.02160795, 0.72131929, 0.90667005,
       0.41976059, 0.2249799 , 0.77308574, 0.23680202, 0.87219601,
       0.31348921, 0.28077657, 0.01421985, 0.18433817, 0.20701236,
       0.32259584, 0.82455516, 0.38019921, 0.13563128, 0.80461792,
       0.11045527, 0.46412069, 0.43063762, 0.25785438, 0.08767418,
       0.99228704, 0.83626804, 0.26058467, 0.02977397, 0.85778

In [69]:
np.random.rand(5,3)

array([[0.14754537, 0.64488026, 0.94632929],
       [0.30507097, 0.45334249, 0.0214618 ],
       [0.58942142, 0.15876753, 0.36839209],
       [0.09112259, 0.94852759, 0.61277869],
       [0.40729502, 0.26798913, 0.36254689]])

In [191]:
# Creating array from uniform distribution ,“Uniform distribution” means all values in [0,1) are equally likely
new_arr=np.random.rand(5,3)
# 2 dimensional array of shape (5,3) 

In [192]:
new_arr

array([[0.62946008, 0.84249922, 0.53649187],
       [0.78046082, 0.43496661, 0.32314891],
       [0.63135669, 0.00963159, 0.62189804],
       [0.78807364, 0.79179865, 0.38020287],
       [0.8779192 , 0.65197235, 0.70383045]])

In [193]:
np.random.rand(3,3)

array([[0.75491144, 0.07038822, 0.9812041 ],
       [0.38657174, 0.4550226 , 0.03801391],
       [0.25475692, 0.82605983, 0.34950381]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

* For randn, random numbers generated will be in approximately -3 to +3 range.

In [71]:
r1=np.random.randn(10)  # 50 observations from std normal distribution
r1

array([ 0.85235216, -2.56716788, -1.40743938, -0.99497097,  0.85533642,
       -0.4466673 , -1.629996  , -1.63865954, -0.1770499 ,  0.76305884])

In [72]:
r1

array([ 0.85235216, -2.56716788, -1.40743938, -0.99497097,  0.85533642,
       -0.4466673 , -1.629996  , -1.63865954, -0.1770499 ,  0.76305884])

In [73]:
np.mean(r1)

np.float64(-0.6391203539662553)

In [75]:
np.median(r1)

np.float64(-0.7208191342668501)

In [76]:
np.mode(r1)

AttributeError: module 'numpy' has no attribute 'mode'

In [74]:
np.std(r1)

np.float64(1.1441052947531545)

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [82]:
np.random.randint(2,15)

10

In [84]:
np.random.randint(1,100)
# third argument is no. of values. default =1 value

97

In [87]:
np.random.randint(5,100,5)

array([34, 88, 43, 48, 21], dtype=int32)

In [91]:
np.random.randint(40,60,50) # generating 50 values between

array([58, 43, 41, 57, 42, 43, 56, 46, 51, 52, 49, 53, 49, 53, 53, 45, 50,
       46, 48, 58, 48, 57, 49, 56, 49, 47, 53, 48, 42, 43, 55, 49, 40, 55,
       43, 53, 52, 53, 47, 57, 52, 44, 51, 46, 50, 53, 58, 43, 45, 44],
      dtype=int32)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [92]:
arr = np.arange(20)

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [96]:
rand_arr = np.random.randint(0,100,10)

In [101]:
rand_arr

array([99, 57, 26, 63,  3, 24, 11, 26, 51, 85], dtype=int32)

In [102]:
rand_arr.min()

np.int32(3)

In [103]:
rand_arr.max()

np.int32(99)

In [104]:
rand_arr.argmax()

np.int64(0)

In [105]:
rand_arr.argmin()

np.int64(4)

In [ ]:
generate the random integer from 1,200,20 find min,max,argmin,argmax

In [ ]:
# Attributes nothing but information about the array

### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [215]:
arr2=np.random.randint(1,100,20)
arr2

array([83, 95, 18, 21, 19,  2, 77, 15, 64, 43, 79, 13, 99, 84, 84, 15, 78,
       94, 46, 98], dtype=int32)

In [216]:
arr2.max()

np.int32(99)

In [217]:
arr2.min()

np.int32(2)

In [218]:
arr2.argmax()

np.int64(12)

In [219]:
arr2.argmin()

np.int64(5)

In [220]:
arr2.mean()

np.float64(56.35)

---- Phase-1 ------